---
- name: Monitor AVVA pod logs & restart if required
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    namespace: default
    pod_label: "app=avva-app"
    max_restarts: 3
    wait_ready_timeout: 120
    log_tail_lines: 200
    # grep-friendly regex (no (?i) here; grep -i used below)
    failure_grep: "error|failed|exception|panic|traceback"

    ticket_on_failure: true
    ticket_api_url: "https://ascendiondigitalsolutionsdemo1.service-now.com/api/now/table/incident"

    # AWX credential mapped variables (set these in the Job Template -> Credentials -> Survey or extra_vars)
    ticket_auth_user: "{{ sn_user }}"
    ticket_auth_pass: "{{ sn_pass }}"

    ticket_payload:
      short_description: "AVVA pod failed after restarts"
      description: |
        Pod label: {{ pod_label }}
        Namespace: {{ namespace }}
        Attempts: {{ max_restarts }}
        Observed logs: "{{ last_failure_excerpt | default('n/a') }}"

  tasks:

    - name: Find pod name matching label
      command: >
        kubectl get pods -n {{ namespace }} -l "{{ pod_label }}"
        -o jsonpath='{.items[0].metadata.name}'
      register: pod_get
      failed_when: pod_get.stdout == ""
      changed_when: false

    - set_fact:
        pod_name: "{{ pod_get.stdout | trim }}"

    - name: Fetch latest logs (initial check)
      command: kubectl logs {{ pod_name }} -n {{ namespace }} --tail={{ log_tail_lines }}
      register: pod_logs
      failed_when: false
      changed_when: false

    - set_fact:
        failed_match: "{{ (pod_logs.stdout is search('(?i)(' + failure_grep + ')')) | bool }}"
        last_failure_excerpt: "{{ pod_logs.stdout[:400] }}"

    - name: Exit if pod healthy
      meta: end_play
      when: failed_match == false

    ################################################################
    # Single task that does: delete pod -> wait for ready -> check logs
    # This task will be retried up to max_restarts attempts (retries/until)
    ################################################################
    - name: Restart pod and verify health (retries up to max_restarts)
      shell: |
        set -o pipefail
        # delete old pod (ignore error if not found)
        kubectl delete pod {{ pod_name }} -n {{ namespace }} --wait=false || true

        # wait for a new ready pod to appear (timeout defined)
        kubectl wait --for=condition=ready pod -l "{{ pod_label }}" -n {{ namespace }} --timeout={{ wait_ready_timeout }}s

        # get current pod name
        newpod=$(kubectl get pods -n {{ namespace }} -l "{{ pod_label }}" -o jsonpath='{.items[0].metadata.name}')

        # fetch logs and check for failure strings (grep -i)
        # if grep finds a match -> exit 1 (meaning unhealthy), otherwise exit 0
        kubectl logs -n {{ namespace }} "${newpod}" --tail={{ log_tail_lines }} | grep -Ei "{{ failure_grep }}" && exit 1 || exit 0
      register: restart_check
      failed_when: false
      retries: "{{ max_restarts }}"
      delay: 5
      until: restart_check.rc == 0

    - name: Set final state facts
      set_fact:
        final_failed: "{{ restart_check is defined and restart_check.rc != 0 }}"

    - name: Capture last logs for ticket (if final_failed)
      when: final_failed
      block:
        - name: Get current pod name (final)
          command: kubectl get pods -n {{ namespace }} -l "{{ pod_label }}" -o jsonpath='{.items[0].metadata.name}'
          register: pod_current
        - name: Get last logs excerpt
          command: kubectl logs -n {{ namespace }} {{ pod_current.stdout | trim }} --tail={{ log_tail_lines }}
          register: final_logs
        - set_fact:
            last_failure_excerpt: "{{ final_logs.stdout[:800] }}"

    - name: Create ServiceNow ticket if failure continues
      when: final_failed and ticket_on_failure
      uri:
        url: "{{ ticket_api_url }}"
        method: POST
        user: "{{ ticket_auth_user }}"
        password: "{{ ticket_auth_pass }}"
        force_basic_auth: yes
        status_code: 200,201
        headers:
          Content-Type: "application/json"
        body: "{{ ticket_payload | to_json }}"
      register: ticket_result

    - debug:
        msg: "Monitoring finished. final_failed={{ final_failed }}. pod={{ pod_name }}"

    - debug:
        var: ticket_result.json
      when: final_failed and ticket_on_failure
